fix: version format for msi (#8)

diff --git a/.github/workflows/tauri-build.yml b/.github/workflows/tauri-build.yml
--- a/.github/workflows/tauri-build.yml
+++ b/.github/workflows/tauri-build.yml
@@ -71,7 +71,12 @@ jobs:
         if: inputs.version != ''
         shell: bash
         run: |
-          VERSION=${{ inputs.version }}
+          VERSION=$(echo "${{ inputs.version }}" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
+
+          if [ -z "$VERSION" ]; then
+            echo "Error: Invalid version format. Must be major.minor.patch"
+            exit 1
+          fi
 
           # Update version in tauri.conf.json
           TAURI_FILEPATH="./src-tauri/tauri.conf.json"
